language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'

os:
- linux

env:
- ARCH=x86_64
- ARCH=i686

install:
- pip install requests faker nose

script:
- pyflakes mixnode/*.py || true
- python setup.py install
- python setup.py nosetests